import type { ReactNode } from "react";
import { Providers } from "~/components/providers";
import { Mic, Zap, Layers } from "lucide-react";
import Link from "next/link";

export default function AuthLayout({ children }: { children: ReactNode }) {
  return (
    <Providers>
      <div className="flex min-h-screen bg-neutral-950 text-neutral-100">
        {/* Left Side – Branding */}
        <div className="relative hidden lg:flex lg:w-1/2 flex-col justify-center px-14 overflow-hidden">
          {/* Background */}
          <div className="absolute inset-0 bg-gradient-to-br from-neutral-900 via-neutral-950 to-black" />
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_30%,rgba(255,255,255,0.06),transparent_60%)]" />

          <div className="relative z-10 max-w-md">
            {/* Logo */}
            <Link href="/" className="mb-14 flex items-center gap-3">
              <div className="flex h-11 w-11 items-center justify-center rounded-xl border border-neutral-700 bg-neutral-900">
                <Mic className="h-5 w-5 text-neutral-200" />
              </div>
              <span className="text-xl font-semibold tracking-tight">
                VoiceStudio
              </span>
            </Link>

            {/* Heading */}
            <h1 className="mb-6 text-4xl font-semibold leading-tight">
              Human-like voices,
              <br />
              generated by AI
            </h1>

            <p className="mb-10 text-neutral-400 leading-relaxed">
              A focused platform for generating clean, natural-sounding speech
              using modern AI models. Built for creators, teams, and real use
              cases.
            </p>

            {/* Features */}
            <div className="space-y-5">
              {[
                {
                  icon: Mic,
                  text: "High quality voice synthesis",
                },
                {
                  icon: Zap,
                  text: "Fast and reliable generation",
                },
                {
                  icon: Layers,
                  text: "Organized projects and exports",
                },
              ].map((item, i) => (
                <div key={i} className="flex items-center gap-4">
                  <div className="flex h-10 w-10 items-center justify-center rounded-lg border border-neutral-700 bg-neutral-900">
                    <item.icon className="h-5 w-5 text-neutral-300" />
                  </div>
                  <span className="text-neutral-300">{item.text}</span>
                </div>
              ))}
            </div>

            {/* Subtle stats */}
            <div className="mt-16 grid grid-cols-3 gap-6 text-center">
              <div>
                <div className="text-lg font-medium">10k+</div>
                <div className="text-xs text-neutral-500">Generations</div>
              </div>
              <div>
                <div className="text-lg font-medium">Multi-lang</div>
                <div className="text-xs text-neutral-500">Support</div>
              </div>
              <div>
                <div className="text-lg font-medium">Cloud</div>
                <div className="text-xs text-neutral-500">Based</div>
              </div>
            </div>
          </div>
        </div>

        {/* Right Side – Auth */}
        <div className="flex flex-1 flex-col justify-center bg-neutral-950 px-6 py-12">
          <div className="mx-auto w-full max-w-md">
            {/* Mobile Logo */}
            <div className="mb-10 text-center lg:hidden">
              <Link href="/" className="inline-flex items-center gap-2">
                <div className="flex h-9 w-9 items-center justify-center rounded-lg border border-neutral-700 bg-neutral-900">
                  <Mic className="h-5 w-5 text-neutral-200" />
                </div>
                <span className="text-lg font-semibold">VoiceStudio</span>
              </Link>
            </div>

            {/* Auth Form */}
            <div className="rounded-xl border border-neutral-800 bg-neutral-900/60 p-6 shadow-lg backdrop-blur">
              {children}
            </div>

            {/* Footer */}
            <p className="mt-6 text-center text-sm text-neutral-500">
              Return to{" "}
              <Link
                href="/"
                className="text-neutral-300 hover:text-white transition"
              >
                homepage
              </Link>
            </p>
          </div>
        </div>
      </div>
    </Providers>
  );
}
